In [1]:
#Cleaning & merge 2019,2020
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Study data files
path1 = "Resources/2019.csv"
path2 = "Resources/2020.csv"
# Read the mouse data and the study results
data1 = pd.read_csv(path1)

data2 = pd.read_csv(path2)

data1.head()

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298

In [3]:
data1["Country or region"].unique()

array(['Finland', 'Denmark', 'Norway', 'Iceland', 'Netherlands',
       'Switzerland', 'Sweden', 'New Zealand', 'Canada', 'Austria',
       'Australia', 'Costa Rica', 'Israel', 'Luxembourg',
       'United Kingdom', 'Ireland', 'Germany', 'Belgium', 'United States',
       'Czech Republic', 'United Arab Emirates', 'Malta', 'Mexico',
       'France', 'Taiwan', 'Chile', 'Guatemala', 'Saudi Arabia', 'Qatar',
       'Spain', 'Panama', 'Brazil', 'Uruguay', 'Singapore', 'El Salvador',
       'Italy', 'Bahrain', 'Slovakia', 'Trinidad & Tobago', 'Poland',
       'Uzbekistan', 'Lithuania', 'Colombia', 'Slovenia', 'Nicaragua',
       'Kosovo', 'Argentina', 'Romania', 'Cyprus', 'Ecuador', 'Kuwait',
       'Thailand', 'Latvia', 'South Korea', 'Estonia', 'Jamaica',
       'Mauritius', 'Japan', 'Honduras', 'Kazakhstan', 'Bolivia',
       'Hungary', 'Paraguay', 'Northern Cyprus', 'Peru', 'Portugal',
       'Pakistan', 'Russia', 'Philippines', 'Serbia', 'Moldova', 'Libya',
       'Montenegro', 'Tajikistan', 'Croatia', 'Hong Kong',
       'Dominican Republic', 'Bosnia and Herzegovina', 'Turkey',
       'Malaysia', 'Belarus', 'Greece', 'Mongolia', 'North Macedonia',
       'Nigeria', 'Kyrgyzstan', 'Turkmenistan', 'Algeria', 'Morocco',
       'Azerbaijan', 'Lebanon', 'Indonesia', 'China', 'Vietnam', 'Bhutan',
       'Cameroon', 'Bulgaria', 'Ghana', 'Ivory Coast', 'Nepal', 'Jordan',
       'Benin', 'Congo (Brazzaville)', 'Gabon', 'Laos', 'South Africa',
       'Albania', 'Venezuela', 'Cambodia', 'Palestinian Territories',
       'Senegal', 'Somalia', 'Namibia', 'Niger', 'Burkina Faso',
       'Armenia', 'Iran', 'Guinea', 'Georgia', 'Gambia', 'Kenya',
       'Mauritania', 'Mozambique', 'Tunisia', 'Bangladesh', 'Iraq',
       'Congo (Kinshasa)', 'Mali', 'Sierra Leone', 'Sri Lanka', 'Myanmar',
       'Chad', 'Ukraine', 'Ethiopia', 'Swaziland', 'Uganda', 'Egypt',
       'Zambia', 'Togo', 'India', 'Liberia', 'Comoros', 'Madagascar',
       'Lesotho', 'Burundi', 'Zimbabwe', 'Haiti', 'Botswana', 'Syria',
       'Malawi', 'Yemen', 'Rwanda', 'Tanzania', 'Afghanistan',
       'Central African Republic', 'South Sudan'], dtype=object)

In [4]:
data1=data1.rename(columns={"Country or region":"Country_name"})

In [5]:
data1.head()

,Overall rank,Country_name,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298

In [6]:
data2.head()

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.8087,0.031156,7.869766,7.747634,10.639267,0.954330,71.900825,0.949172,-0.059482,0.195445,1.972317,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857,2.762835
1,Denmark,Western Europe,7.6456,0.033492,7.711245,7.579955,10.774001,0.955991,72.402504,0.951444,0.066202,0.168489,1.972317,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260,2.432741
2,Switzerland,Western Europe,7.5599,0.035014,7.628528,7.491272,10.979933,0.942847,74.102448,0.921337,0.105911,0.303728,1.972317,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946,2.350267
3,Iceland,Western Europe,7.5045,0.059616,7.621347,7.387653,10.772559,0.974670,73.000000,0.948892,0.246944,0.711710,1.972317,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541,2.460688
4,Norway,Western Europe,7.4880,0.034837,7.556281,7.419719,11.087804,0.952487,73.200783,0.955750,0.134533,0.263218,1.972317,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101,2.168266

In [7]:
data2["Country name"].unique()

array(['Finland', 'Denmark', 'Switzerland', 'Iceland', 'Norway',
       'Netherlands', 'Sweden', 'New Zealand', 'Austria', 'Luxembourg',
       'Canada', 'Australia', 'United Kingdom', 'Israel', 'Costa Rica',
       'Ireland', 'Germany', 'United States', 'Czech Republic', 'Belgium',
       'United Arab Emirates', 'Malta', 'France', 'Mexico',
       'Taiwan Province of China', 'Uruguay', 'Saudi Arabia', 'Spain',
       'Guatemala', 'Italy', 'Singapore', 'Brazil', 'Slovenia',
       'El Salvador', 'Kosovo', 'Panama', 'Slovakia', 'Uzbekistan',
       'Chile', 'Bahrain', 'Lithuania', 'Trinidad and Tobago', 'Poland',
       'Colombia', 'Cyprus', 'Nicaragua', 'Romania', 'Kuwait',
       'Mauritius', 'Kazakhstan', 'Estonia', 'Philippines', 'Hungary',
       'Thailand', 'Argentina', 'Honduras', 'Latvia', 'Ecuador',
       'Portugal', 'Jamaica', 'South Korea', 'Japan', 'Peru', 'Serbia',
       'Bolivia', 'Pakistan', 'Paraguay', 'Dominican Republic',
       'Bosnia and Herzegovina', 'Moldova', 'Tajikistan', 'Montenegro',
       'Russia', 'Kyrgyzstan', 'Belarus', 'North Cyprus', 'Greece',
       'Hong Kong S.A.R. of China', 'Croatia', 'Libya', 'Mongolia',
       'Malaysia', 'Vietnam', 'Indonesia', 'Ivory Coast', 'Benin',
       'Maldives', 'Congo (Brazzaville)', 'Azerbaijan', 'Macedonia',
       'Ghana', 'Nepal', 'Turkey', 'China', 'Turkmenistan', 'Bulgaria',
       'Morocco', 'Cameroon', 'Venezuela', 'Algeria', 'Senegal', 'Guinea',
       'Niger', 'Laos', 'Albania', 'Cambodia', 'Bangladesh', 'Gabon',
       'South Africa', 'Iraq', 'Lebanon', 'Burkina Faso', 'Gambia',
       'Mali', 'Nigeria', 'Armenia', 'Georgia', 'Iran', 'Jordan',
       'Mozambique', 'Kenya', 'Namibia', 'Ukraine', 'Liberia',
       'Palestinian Territories', 'Uganda', 'Chad', 'Tunisia',
       'Mauritania', 'Sri Lanka', 'Congo (Kinshasa)', 'Swaziland',
       'Myanmar', 'Comoros', 'Togo', 'Ethiopia', 'Madagascar', 'Egypt',
       'Sierra Leone', 'Burundi', 'Zambia', 'Haiti', 'Lesotho', 'India',
       'Malawi', 'Yemen', 'Botswana', 'Tanzania',
       'Central African Republic', 'Rwanda', 'Zimbabwe', 'South Sudan',
       'Afghanistan'], dtype=object)

In [8]:
data2=data2.drop(columns={"Standard error of ladder score","upperwhisker","lowerwhisker","Logged GDP per capita","Social support","Generosity","Perceptions of corruption","Ladder score in Dystopia","Dystopia + residual","Healthy life expectancy","Freedom to make life choices"})
data2.head()

,Country name,Regional indicator,Ladder score,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,Western Europe,7.8087,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857
1,Denmark,Western Europe,7.6456,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260
2,Switzerland,Western Europe,7.5599,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946
3,Iceland,Western Europe,7.5045,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541
4,Norway,Western Europe,7.4880,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101

In [26]:
data2=data2.rename(columns={"Regional indicator":"Regional_indicator","Country name":"Country_name","Ladder score":"Score","Explained by: Log GDP per capita":"GDP per capita","Explained by: Social support":"Social support","Explained by: Healthy life expectancy":"Healthy life expectancy","Explained by: Freedom to make life choices":"Freedom to make life choices","Explained by: Generosity":"Generosity","Explained by: Perceptions of corruption":"Perceptions of corruption"})
data2.head()

,Country_name,Regional_indicator,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,Finland,Western Europe,7.8087,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857
1,Denmark,Western Europe,7.6456,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260
2,Switzerland,Western Europe,7.5599,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946
3,Iceland,Western Europe,7.5045,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541
4,Norway,Western Europe,7.4880,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101

In [27]:
# Combine the data into a single dataset
merge_df = pd.merge(data2,data1, on="Country_name", how= "left",suffixes=('_2020', '_2019'))
merge_df.head()

,Country_name,Regional_indicator,Score_2020,GDP per capita_2020,Social support_2020,Healthy life expectancy_2020,Freedom to make life choices_2020,Generosity_2020,Perceptions of corruption_2020,Overall rank,Score_2019,GDP per capita_2019,Social support_2019,Healthy life expectancy_2019,Freedom to make life choices_2019,Generosity_2019,Perceptions of corruption_2019
0,Finland,Western Europe,7.8087,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857,1.0,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,Denmark,Western Europe,7.6456,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260,2.0,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,Switzerland,Western Europe,7.5599,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946,6.0,7.480,1.452,1.526,1.052,0.572,0.263,0.343
3,Iceland,Western Europe,7.5045,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541,4.0,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,Norway,Western Europe,7.4880,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101,3.0,7.554,1.488,1.582,1.028,0.603,0.271,0.341

### Questions to solve

* Which is the most happy region in 2019? in 2020? (Solved)
* Top 5 [Countries] 2019 & 2020 (Solved)
* Last 5 [Countries] 2019 & 2020 (Solved)
* Analisis by region (Solved)
* Analize Mexico changes for 2019 & 2020 (Solved)
* Healthy life expectancy changes for 19, 2020
* Correlation between factors & score per year

In [28]:
merge_df["Score_2020"].max()

7.808700085

In [29]:
merge_df["Score_2020"].min()

2.566900015

In [30]:
merge_df["Score_2019"].max()

7.769

In [31]:
merge_df["Score_2019"].min()

2.853

In [32]:
#finding the top 5 for 2020
top=merge_df["Score_2020"].nlargest()
top2_df=pd.DataFrame(top)
top2_df["Country_name"]=merge_df["Country_name"]
top2_df
#barplot

   Score_2020 Country_name
0      7.8087      Finland
1      7.6456      Denmark
2      7.5599  Switzerland
3      7.5045      Iceland
4      7.4880       Norway

In [33]:
#finding top 5 2019
top=merge_df["Score_2019"].nlargest()
top1_df=pd.DataFrame(top)
top1_df["Country_name"]=merge_df["Country_name"]
top1_df
#barplot

   Score_2019 Country_name
0       7.769      Finland
1       7.600      Denmark
4       7.554       Norway
3       7.494      Iceland
5       7.488  Netherlands

In [18]:
tail=merge_df["Score_2019"].tail()
tail1_df=pd.DataFrame(tail)
tail1_df.sort_values(by='Score_2019',ascending=True)
tail1_df["Country_name"]=merge_df["Country_name"]
tail1_df

     Score_2019              Country_name
148       3.083  Central African Republic
149       3.334                    Rwanda
150       3.663                  Zimbabwe
151       2.853               South Sudan
152       3.203               Afghanistan

In [19]:
tail=merge_df["Score_2020"].tail()
tail2_df=pd.DataFrame(tail)
tail2_df.sort_values(by=['Score_2020'])
tail2_df["Country_name"]=merge_df["Country_name"]
tail2_df

     Score_2020              Country_name
148      3.4759  Central African Republic
149      3.3123                    Rwanda
150      3.2992                  Zimbabwe
151      2.8166               South Sudan
152      2.5669               Afghanistan

In [22]:
Mex_df=merge_df.query('Country_name == "Mexico"')
Mex_df

,Country_name,Regional indicator,Score_2020,GDP per capita_2020,Social support_2020,Healthy life expectancy_2020,Freedom to make life choices_2020,Generosity_2020,Perceptions of corruption_2020,Overall rank,Score_2019,GDP per capita_2019,Social support_2019,Healthy life expectancy_2019,Freedom to make life choices_2019,Generosity_2019,Perceptions of corruption_2019
23,Mexico,Latin America and Caribbean,6.465,1.024387,1.226333,0.831601,0.553893,0.083094,0.083134,23.0,6.595,1.07,1.323,0.861,0.433,0.074,0.073

In [40]:
merge_df["Regional_indicator"].unique()

array(['Western Europe', 'North America and ANZ',
       'Middle East and North Africa', 'Latin America and Caribbean',
       'Central and Eastern Europe', 'East Asia', 'Southeast Asia',
       'Commonwealth of Independent States', 'Sub-Saharan Africa',
       'South Asia'], dtype=object)

In [51]:
Regional_df=merge_df.groupby(by=["Regional_indicator"]).mean()
Regional_df

,Score_2020,GDP per capita_2020,Social support_2020,Healthy life expectancy_2020,Freedom to make life choices_2020,Generosity_2020,Perceptions of corruption_2020,Overall rank,Score_2019,GDP per capita_2019,Social support_2019,Healthy life expectancy_2019,Freedom to make life choices_2019,Generosity_2019,Perceptions of corruption_2019
Regional_indicator,,,,,,,,,,,,,,,
Central and Eastern Europe,5.883818,1.079527,1.311129,0.826199,0.447895,0.131079,0.054702,59.250000,5.808375,1.130000,1.369812,0.857875,0.357438,0.124687,0.039563
Commonwealth of Independent States,5.358342,0.841350,1.268998,0.702987,0.464354,0.171706,0.122152,85.500000,5.256333,0.879000,1.301167,0.742667,0.358667,0.163250,0.093667
East Asia,5.714850,1.185275,1.276376,0.932255,0.436815,0.164634,0.150638,72.000000,5.564250,1.151250,1.323500,0.921000,0.360500,0.134250,0.083500
Latin America and Caribbean,5.981786,0.871039,1.269381,0.774657,0.520302,0.151457,0.086553,52.000000,5.942550,0.908950,1.332850,0.816800,0.438500,0.142600,0.074850
Middle East and North Africa,5.227159,0.998307,1.127260,0.724121,0.375862,0.143173,0.112388,84.411765,5.274529,1.048176,1.184353,0.762294,0.321941,0.139118,0.099235
North America and ANZ,7.173525,1.307087,1.451136,0.971216,0.611826,0.307593,0.325313,11.750000,7.176250,1.368250,1.516750,0.993750,0.545000,0.306750,0.276500
South Asia,4.475443,0.640591,0.920061,0.620979,0.449734,0.222228,0.093571,119.333333,4.434333,0.623167,0.931167,0.619167,0.374500,0.212167,0.081167
Southeast Asia,5.383367,0.890821,1.191915,0.702408,0.618563,0.306065,0.148924,85.111111,5.273667,0.930000,1.246444,0.745333,0.543778,0.301778,0.123444
Sub-Saharan Africa,4.383495,0.437448,0.856232,0.356113,0.387285,0.200586,0.106646,125.128205,4.290615,0.455128,0.922282,0.411128,0.331667,0.186308,0.090000
Western Europe,6.899219,1.300418,1.402224,0.995932,0.549439,0.224752,0.262678,21.350000,6.898400,1.362050,1.483900,1.013850,0.482550,0.221050,0.221200